version: "3.8"

services:
  check:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    volumes:
      - .:/app

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  # Database for testing

  test-postgres:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate
