version: "3.8"

services:
  check:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    volumes:
      - .:/app

  test-db:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: medbook
      POSTGRES_USER: medbook
      POSTGRES_PASSWORD: medbook

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: medbook
      POSTGRES_USER: medbook
      POSTGRES_PASSWORD: medbook

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  chromedriver-host:
      image: robcherry/docker-chromedriver:77
      network_mode: host
      ports:
        - 4444:4444
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ''

  chromedriver-ci:
    image: robcherry/docker-chromedriver:77
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ''
