version: "3.8"

services:
  check:
    # TODO: update with formatter up to 0.2.0
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    volumes:
      - .:/app

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: medbook
      POSTGRES_USER: medbook
      POSTGRES_PASSWORD: medbook

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db


  # Testing

  chromedriver-host:
      image: robcherry/docker-chromedriver:77
      network_mode: host
      ports:
        - 4444:4444
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ''

  test-db:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: medbook
      POSTGRES_USER: medbook
      POSTGRES_PASSWORD: medbook

  test:
    image: abogoyavlensky/clojure-openjdk11-build:0.2.0
    depends_on:
      - test-db
    environment:
      MEDBOOK_DB_URL: "jdbc:postgresql://test-db:5432/medbook?user=medbook&password=medbook"
      TESTING_ENV: "ci"
    volumes:
      - .:/app
