version: "3.8"

services:
  check:
    image: abogoyavlensky/clojure-openjdk11-build:0.2.0
    volumes:
      - .:/app

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medbook
      POSTGRES_USER: medbook
      POSTGRES_PASSWORD: medbook

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db


  # Testing

  test-db:
    image: postgres:14-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: medbook
      POSTGRES_USER: medbook
      POSTGRES_PASSWORD: medbook

  test:
    image: abogoyavlensky/clojure-openjdk11-build:0.2.0
    depends_on:
      - test-db
    environment:
      MEDBOOK_DB_URL_TEST: "jdbc:postgresql://test-db:5432/medbook?user=medbook&password=medbook"
    volumes:
      - .:/app
