apiVersion: apps/v1
kind: Deployment
metadata:
  name: medbook
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: medbook
  template:
    metadata:
      labels:
        app: medbook
    spec:
      containers:
        - name: medbook
          image: abogoyavlensky/medbook:0.0.1-SNAPSHOT-4
          ports:
            - containerPort: 8000
          env:
            - name: MEDBOOK_DB_URL
              valueFrom:
                secretKeyRef:
                  name: medbook-db-url
                  key: medbook_db_url.txt
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: medbook
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: medbook

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medbook-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "medbook.bogoyavlensky.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: medbook
                port:
                  number: 80
