name: Checks


on:
  push:
#     TODO: fix to master
    branches: [ deploy ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: 1.70.0

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ams3-staging

      - name: Deploy to kubernetes
        run: |
          kubectl version
          kubectl get pods
