name: Checks


on:
  push:
#     TODO: fix to master
    branches: [ deploy ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to kubernetes
        run: kubectl --help
