name: Checks


on:
  push:
#     TODO: fix to master
    branches: [ deploy ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to kubernetes
        run: |
          kubectl --kubeconfig <(echo $KUBE_CONFIG | base64 --decode) version
          kubectl --kubeconfig <(echo $KUBE_CONFIG | base64 --decode) config view
        env:
          KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
