name: Checks


on:
  push:
#     TODO: fix to master
    branches: [ deploy ]


env:
  IMAGE_TAG: abogoyavlensky/medbook:${{ github.sha }}


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: docker-compose run --rm check bash -c "make deps && make lint-init > /dev/null 2>&1 || true && make lint"

      - name: Fmt
        run: docker-compose run --rm check make fmt-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm test bash -c "mkdir -p target/resources && make deps && make test"

  deploy:
    runs-on: ubuntu-latest
    needs: [check, test]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
      - uses: actions/checkout@v2

      - name: Run db migrations
        run: docker-compose run --rm check bash -c "clojure -X:migrations migrate :jdbc-url $MEDBOOK_DB_URL"
        env:
          MEDBOOK_DB_URL: ${{ secrets.MEDBOOK_DB_URL}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push new image
        run: | 
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: 1.70.0

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ams3-staging

      - name: Deploy to kubernetes
        run: |
          kubectl version
          echo "Image tag: $IMAGE_TAG"
          envsubst < deploy/medbook.yaml | kubectl apply -f -

      - name: Verify deployment
        run: kubectl rollout status deployment/medbook
