name: Checks


on:
  push:
#     TODO: fix to master
    branches: [ deploy ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to kubernetes
        run: |
          kubectl version
          mkdir -p $HOME/.kube
#          echo -n ${{ KUBE_CONFIG }} | base64 -d > $HOME/.kube/config
#          kubectl config view
