name: Checks


on:
  push:
#     TODO: fix to master
    branches: [ deploy ]

env:
  IMAGE_TAG: abogoyavlensky/medbook:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push new image
        run: | 
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: 1.70.0

#      - name: Save DigitalOcean kubeconfig
#        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ams3-staging
#
#      - name: Deploy to kubernetes
#        run: |
#          kubectl version
#          echo "Image version: abogoyavlensky/medbook:$IMAGE_VERSION"
#          envsubst < deploy/medbook.yaml | kubectl apply -f -
#        env:
#          IMAGE_VERSION: ${{ github.sha }}
#
#      - name: Verify deployment
#        run: kubectl rollout status deployment/medbook
